'use strict';
const $=id=>document.getElementById(id);
const state={z:null,base:null,shape:[],status:null,model:null,c:0,t:0,y:0,x:0,limit:3,tab:'latent',
  weight:null,weightInfo:null,wi:0,wo:0,wp:0,traceLayer:null,activation:null,activationMeta:null,ay:0,ax:0,
  result:null,rgb:null,ry:0,rx:0,editPending:false,drag:null,completed:new Set(),weightRequest:0,activationRequest:0,rgbRequest:0};
function fail(e){$('error').textContent=String(e.message||e);$('error').hidden=false;}
function clearError(){$('error').hidden=true;}
function on(id,event,fn){$(id).addEventListener(event,e=>Promise.resolve().then(()=>fn(e)).catch(fail));}
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.error||response.statusText);return data;}
async function binary(path){const r=await fetch(path);if(!r.ok){const e=await r.json();throw Error(e.error);}return {array:new Float32Array(await r.arrayBuffer()),shape:JSON.parse(r.headers.get('X-Shape')),revision:Number(r.headers.get('X-Revision'))};}
const clamp=(x,min,max)=>Number.isFinite(x)&&Number.isFinite(max)?Math.min(max,Math.max(min,x)):min;
const integer=(id,max)=>clamp(Math.trunc(Number($(id).value))||0,0,max);
const fmt=x=>Number.isFinite(x)?Number(x).toPrecision(9):'—';
function offset(c,t,y,x){const [,T,H,W]=state.shape;return ((c*T+t)*H+y)*W+x;}
function value(){return state.z[offset(state.c,state.t,state.y,state.x)];}
function color(v,limit){const f=Math.min(1,Math.abs(v)/Math.max(1e-10,limit));const target=v<0?[55,107,164]:[187,77,56];return target.map(n=>Math.round(250+(n-250)*f));}
function canvasImage(data,h,w,limit){const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');const pixels=ctx.createImageData(w,h);for(let i=0;i<data.length;i++){const rgb=color(data[i],limit);pixels.data.set([...rgb,255],i*4);}ctx.putImageData(pixels,0,0);return canvas;}
function plane(canvas,data,h,w,limit,y=-1,x=-1){canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.drawImage(canvasImage(data,h,w,limit),0,0);if(y>=0){ctx.strokeStyle='#121212';ctx.lineWidth=Math.max(.3,w/650);ctx.strokeRect(x+.05,y+.05,.9,.9);}}
function cube(canvas,data,h,w,depth,t,limit,selected=false,label='t'){
  const cw=280,ch=190;canvas.width=cw;canvas.height=ch;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,cw,ch);
  const pw=Math.min(228,128*w/h),ph=pw*h/w,dx=depth>1?26:0,dy=depth>1?-24:0,frontX=(280-pw-dx)/2,frontY=41,ratio=depth>1?t/(depth-1):0;
  const y0=frontY+(128-ph)/2;ctx.strokeStyle='#aaa';ctx.lineWidth=1;
  const rect=(x,y)=>ctx.strokeRect(x,y,pw,ph);rect(frontX+dx,y0+dy);rect(frontX,y0);
  [[0,0],[pw,0],[pw,ph],[0,ph]].forEach(([x,y])=>{ctx.beginPath();ctx.moveTo(frontX+x,y0+y);ctx.lineTo(frontX+x+dx,y0+y+dy);ctx.stroke();});
  const sx=frontX+dx*ratio,sy=y0+dy*ratio;ctx.imageSmoothingEnabled=false;ctx.drawImage(canvasImage(data,h,w,limit),sx,sy,pw,ph);ctx.strokeStyle=selected?'#142f50':'#555';ctx.lineWidth=selected?2:1;ctx.strokeRect(sx,sy,pw,ph);
  if(h<=3&&w<=3){ctx.font='11px monospace';ctx.fillStyle='#111';ctx.textAlign='center';for(let y=0;y<h;y++)for(let x=0;x<w;x++)ctx.fillText(data[y*w+x].toPrecision(3),sx+(x+.5)*pw/w,sy+(y+.5)*ph/h+4);ctx.textAlign='left';}
  ctx.fillStyle='#333';ctx.font='11px monospace';ctx.fillText(`${label}=${t} / ${depth-1}`,12,14);ctx.fillText(`W=${w}`,frontX+90,y0+ph+15);ctx.fillText(`H=${h}`,frontX+pw-35,y0+ph+15);
  canvas._geometry={sx,sy,pw,ph,w,h,cw,ch};
}
function pick(event,canvas,h,w){const r=canvas.getBoundingClientRect();return [clamp(Math.floor((event.clientY-r.top)/r.height*h),0,h-1),clamp(Math.floor((event.clientX-r.left)/r.width*w),0,w-1)];}
function cubePick(event,canvas){const g=canvas._geometry,r=canvas.getBoundingClientRect(),x=(event.clientX-r.left)*g.cw/r.width,y=(event.clientY-r.top)*g.ch/r.height;return [clamp(Math.floor((y-g.sy)/g.ph*g.h),0,g.h-1),clamp(Math.floor((x-g.sx)/g.pw*g.w),0,g.w-1)];}
function switchTab(name){state.tab=name;document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===name)));document.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.id!==name);window.scrollTo({top:0});}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));

function makeVolumes(){const grid=$('volume-grid');grid.replaceChildren();for(let c=0;c<16;c++){
  const box=document.createElement('div');box.className='volume';box.dataset.c=c;
  const head=document.createElement('div');head.className='volume-head';const button=document.createElement('button');button.textContent=`channel ${String(c).padStart(2,'0')}`;button.onclick=()=>{state.c=c;renderLatent();};const stat=document.createElement('span');stat.className='mini-stat';head.append(button,stat);
  const canvas=document.createElement('canvas');canvas.setAttribute('aria-label',`channel ${c} 时间截面，滚轮切换时间，点击选择像素`);canvas.addEventListener('click',e=>{state.c=c;[state.y,state.x]=cubePick(e,canvas);renderLatent();});canvas.addEventListener('wheel',e=>{e.preventDefault();setTime(state.t+Math.sign(e.deltaY));},{passive:false});box.append(head,canvas);grid.append(box);
}}
function setTime(t){if(state.drag||!state.z)return;state.t=clamp(t,0,state.shape[1]-1);renderLatent();}
function renderLatent(){if(!state.z)return;const [C,T,H,W]=state.shape;
  $('shape').textContent=`[${state.shape.join(', ')}] = ${state.z.length.toLocaleString()} scalars`;
  $('time-number').max=$('time-range').max=T-1;$('time-number').value=$('time-range').value=state.t;$('time-label').textContent=`t=${state.t}，共 ${T} 层`;
  document.querySelectorAll('#volume-grid .volume').forEach((box,c)=>{const a=offset(c,state.t,0,0),data=state.z.subarray(a,a+H*W);box.classList.toggle('active',c===state.c);cube(box.querySelector('canvas'),data,H,W,T,state.t,state.limit,c===state.c);let min=Infinity,max=-Infinity;for(const v of data){min=Math.min(min,v);max=Math.max(max,v);}box.querySelector('.mini-stat').textContent=`${min.toFixed(2)}…${max.toFixed(2)}`;});
  const a=offset(state.c,state.t,0,0);plane($('latent-plane'),state.z.subarray(a,a+H*W),H,W,state.limit,state.y,state.x);$('slice-title').textContent=`c=${state.c}, t=${state.t}`;
  ['c','t','y','x'].forEach((key,i)=>{$('coord-'+key).max=state.shape[i]-1;$('coord-'+key).value=state[key];});
  renderScalar();numberGrid($('number-grid'),state.z.subarray(a,a+H*W),H,W,state.y,state.x,true);
}
function renderScalar(){const v=value();$('address').textContent=`z[${state.c}, ${state.t}, ${state.y}, ${state.x}]`;$('scalar-scrub').textContent=fmt(v);if(document.activeElement!==$('scalar-value'))$('scalar-value').value=String(v);const original=state.base[offset(state.c,state.t,state.y,state.x)];$('baseline-value').textContent=`初始 ${fmt(original)}；Δ ${fmt(v-original)}`;}
function numberGrid(table,data,h,w,cy,cx,editable=false){table.replaceChildren();const radius=3,y0=Math.max(0,Math.min(h-7,cy-radius)),x0=Math.max(0,Math.min(w-9,cx-4));const head=document.createElement('tr');head.append(document.createElement('th'));for(let x=x0;x<Math.min(w,x0+9);x++){const th=document.createElement('th');th.textContent=`x=${x}`;head.append(th);}table.append(head);
  for(let y=y0;y<Math.min(h,y0+7);y++){const row=document.createElement('tr'),th=document.createElement('th');th.textContent=`y=${y}`;row.append(th);for(let x=x0;x<Math.min(w,x0+9);x++){const td=document.createElement('td');td.textContent=data[y*w+x].toFixed(5);td.title=`[${y},${x}] = ${data[y*w+x]}`;td.classList.toggle('selected',y===cy&&x===cx);if(editable){td.dataset.edit='true';td.addEventListener('pointerdown',e=>{state.y=y;state.x=x;startDrag(e,td);});td.addEventListener('dblclick',()=>{$('scalar-value').focus();$('scalar-value').select();});}row.append(td);}table.append(row);}}
function startDrag(e,target){if(e.button!==0||state.editPending)return;e.preventDefault();const initial=value(),index=offset(state.c,state.t,state.y,state.x);state.drag={initial,index,startY:e.clientY,moved:false,target};target.setPointerCapture(e.pointerId);renderScalar();
  const move=ev=>{if(!state.drag)return;const distance=state.drag.startY-ev.clientY;if(Math.abs(distance)>2)state.drag.moved=true;if(!state.drag.moved)return;state.z[index]=initial+distance*(ev.shiftKey?.001:.01);renderScalar();target.textContent=fmt(state.z[index]);};
  const finish=async ev=>{target.removeEventListener('pointermove',move);target.removeEventListener('pointerup',finish);target.removeEventListener('pointercancel',cancel);const moved=state.drag?.moved;state.drag=null;if(target.hasPointerCapture(ev.pointerId))target.releasePointerCapture(ev.pointerId);if(moved)renderLatent();else{document.querySelectorAll('#number-grid td').forEach(td=>td.classList.toggle('selected',td===target));const [,T,H,W]=state.shape;const a=offset(state.c,state.t,0,0);plane($('latent-plane'),state.z.subarray(a,a+H*W),H,W,state.limit,state.y,state.x);}if(moved)try{await saveScalar(state.z[index]);}catch(error){state.z[index]=initial;renderLatent();fail(error);}};
  const cancel=ev=>{state.z[index]=initial;state.drag=null;target.removeEventListener('pointermove',move);target.removeEventListener('pointerup',finish);target.removeEventListener('pointercancel',cancel);renderLatent();};
  target.addEventListener('pointermove',move);target.addEventListener('pointerup',finish);target.addEventListener('pointercancel',cancel);
}
async function saveScalar(v){if(!Number.isFinite(v))throw Error('请输入有限数值');if(state.editPending)throw Error('上一笔编辑尚未完成');state.editPending=true;try{clearError();state.status=await api('/api/edit',{revision:state.status.revision,c:state.c,t:state.t,y:state.y,x:state.x,mode:'scalar',value:v});state.z[offset(state.c,state.t,state.y,state.x)]=v;renderLatent();renderStatus();}catch(e){await reloadLatent();throw e;}finally{state.editPending=false;}}
async function reloadLatent(withBase=false){const z=await binary('/api/latent');state.z=z.array;state.shape=z.shape;state.status=await api('/api/status');if(withBase||!state.base){state.base=(await binary('/api/baseline')).array;}['c','t','y','x'].forEach((k,i)=>state[k]=clamp(state[k],0,z.shape[i]-1));renderLatent();renderStatus();}
on('time-number','input',()=>setTime(integer('time-number',state.shape[1]-1)));on('time-range','input',()=>setTime(+$('time-range').value));on('color-limit','change',()=>{state.limit=Math.max(.1,Number($('color-limit').value)||3);$('color-limit').value=state.limit;renderLatent();});
['c','t','y','x'].forEach((k,i)=>on('coord-'+k,'input',()=>{state[k]=integer('coord-'+k,state.shape[i]-1);renderLatent();}));
on('latent-plane','click',e=>{[state.y,state.x]=pick(e,$('latent-plane'),state.shape[2],state.shape[3]);renderLatent();});
$('latent-plane').addEventListener('wheel',e=>{e.preventDefault();setTime(state.t+Math.sign(e.deltaY));},{passive:false});
on('latent-plane','mousemove',e=>{const [y,x]=pick(e,$('latent-plane'),state.shape[2],state.shape[3]);$('plane-hover').textContent=`z[${state.c},${state.t},${y},${x}] = ${fmt(state.z[offset(state.c,state.t,y,x)])}`;});
$('scalar-scrub').addEventListener('pointerdown',e=>startDrag(e,$('scalar-scrub')));
on('scalar-scrub','keydown',e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();return saveScalar(value()+(e.key==='ArrowUp'?1:-1)*(e.shiftKey?.001:.01));}});
on('set-scalar','click',()=>saveScalar(Number($('scalar-value').value)));on('scalar-value','keydown',e=>{if(e.key==='Enter')return saveScalar(Number($('scalar-value').value));});
on('apply-region','click',async()=>{clearError();state.status=await api('/api/edit',{revision:state.status.revision,c:state.c,t:state.t,y:state.y,x:state.x,mode:$('edit-mode').value,value:Number($('delta').value),extent:['t','y','x'].map(k=>Number($('extent-'+k).value))});await reloadLatent();});
on('initialize','click',async()=>{clearError();const shape=$('preset').value==='full'?[16,21,60,104]:[16,5,12,20];await api('/api/reset',{shape,seed:Number($('seed').value)});state.c=state.t=state.y=state.x=0;state.activation=null;state.activationMeta=null;await reloadLatent(true);state.model=await api('/api/model');renderStages();selectStage(state.model.stages[0]);});
on('restore','click',async()=>{await api('/api/restore',{});await reloadLatent();});

function naturalSort(a,b){return a.name.localeCompare(b.name,undefined,{numeric:true});}
function setupWeights(){const list=[...state.model.weights].sort(naturalSort);const select=$('weight-select');select.replaceChildren();for(const info of list){const opt=document.createElement('option');opt.value=info.name;opt.textContent=`${info.name} [${info.shape.join(',')}]`;select.append(opt);}select.value='decoder.1.weight';const table=$('weight-inventory');table.innerHTML='<tr><th>tensor</th><th>shape</th><th>parameters</th><th>min</th><th>max</th></tr>';for(const item of list){const row=document.createElement('tr');for(const v of [item.name,item.shape.join(' × '),item.parameters,item.minimum.toPrecision(5),item.maximum.toPrecision(5)]){const td=document.createElement('td');td.textContent=v;row.append(td);}table.append(row);}return loadWeight();}
async function loadWeight(){const request=++state.weightRequest;const name=$('weight-select').value;const b=await binary('/api/weight?name='+encodeURIComponent(name));if(request!==state.weightRequest)return;state.weight=b.array;state.weightInfo=state.model.weights.find(x=>x.name===name);state.wi=state.wo=state.wp=0;renderWeights();}
function renderWeights(){if(!state.weight)return;const info=state.weightInfo,[O,I=1,H=1,W=1]=info.shape;const limit=Math.max(Math.abs(info.minimum),Math.abs(info.maximum),1e-12);
 $('weight-meta').textContent=`[${info.shape.join(', ')}] · ${info.parameters.toLocaleString()} scalars · FP16 → float32（数值不变）`;
 $('weight-input').max=$('weight-range').max=I-1;$('weight-input').value=$('weight-range').value=state.wi;$('weight-input').disabled=$('weight-range').disabled=I===1;$('weight-page').max=Math.ceil(O/16)-1;$('weight-page').value=state.wp;$('weight-page-label').textContent=`第 ${state.wp+1} / ${Math.ceil(O/16)} 页`;
 $('weight-axes').textContent=info.shape.length===1?'bias 是一维向量，不伪装成视频体积；每格对应一个输出通道的偏置。':'[O,I,KH,KW]：盒子数量 = 输出通道 O；截面 = KH×KW；深度 = 输入通道 I。滚轮改变 I，不是时间。每页最多16个盒子。';
 const grid=$('weight-volumes');grid.replaceChildren();for(let o=state.wp*16;o<Math.min(O,(state.wp+1)*16);o++){const box=document.createElement('div');box.className='volume'+(o===state.wo?' active':'');const head=document.createElement('div');head.className='volume-head';head.textContent=`out ${o}`;const canvas=document.createElement('canvas');const start=(o*I+state.wi)*H*W;cube(canvas,state.weight.subarray(start,start+H*W),H,W,I,state.wi,limit,o===state.wo,'in');canvas.addEventListener('click',()=>{state.wo=o;renderWeights();});canvas.addEventListener('wheel',e=>{e.preventDefault();state.wi=clamp(state.wi+Math.sign(e.deltaY),0,I-1);renderWeights();},{passive:false});box.append(head,canvas);grid.append(box);}
 $('kernel-title').textContent=info.shape.length===1?`${info.name}[${state.wo}]`:`${info.name}[${state.wo}, ${state.wi}, :, :]`;
 const table=$('kernel-values');table.replaceChildren();for(let y=0;y<H;y++){const row=document.createElement('tr');for(let x=0;x<W;x++){const td=document.createElement('td');td.textContent=String(state.weight[((state.wo*I+state.wi)*H+y)*W+x]);row.append(td);}table.append(row);}
 $('weight-statistics').textContent=`全 tensor：min=${fmt(info.minimum)} max=${fmt(info.maximum)} mean=${fmt(info.mean)} std=${fmt(info.std)}`;
}
on('weight-select','change',loadWeight);on('weight-input','input',()=>{state.wi=integer('weight-input',(state.weightInfo.shape[1]||1)-1);renderWeights();});on('weight-range','input',()=>{state.wi=+$('weight-range').value;renderWeights();});on('weight-page','input',()=>{state.wp=integer('weight-page',Math.ceil(state.weightInfo.shape[0]/16)-1);state.wo=state.wp*16;renderWeights();});

function renderStages(){const tbody=$('stage-table').querySelector('tbody');tbody.replaceChildren();function row(info,child,parent){const tr=document.createElement('tr');tr.dataset.layer=info.name;if(child){tr.className='child';tr.dataset.parent=parent;tr.hidden=true;}const name=document.createElement('td');const button=document.createElement('button');button.className='stage-name';button.textContent=info.name.replace('decoder.','');button.onclick=()=>selectStage(info);name.append(button);if(info.children?.length){const expand=document.createElement('button');expand.textContent='[+]';expand.setAttribute('aria-label',`展开 ${info.name} 内部操作`);expand.onclick=()=>{const rows=tbody.querySelectorAll(`[data-parent="${info.name}"]`);const show=rows[0].hidden;rows.forEach(r=>r.hidden=!show);expand.textContent=show?'[−]':'[+]';};name.append(expand);}const shape=document.createElement('td');shape.textContent=info.shape.join(' × ');const type=document.createElement('td');type.textContent=info.kind;tr.append(name,shape,type);tbody.append(tr);}
 for(const group of state.model.stages){row(group,false);for(const child of group.children)row(child,true,group.name);}}
function selectStage(info){state.traceLayer=info;$('trace-title').textContent=`${info.name} / ${info.kind}`;$('trace-description').textContent=info.description;$('stage-weights').disabled=!state.model.weights.some(w=>w.name.startsWith(info.name+'.'));$('trace-time').max=info.shape[1]-1;$('trace-time').value=clamp(Number($('trace-time').value),0,info.shape[1]-1);$('trace-channel').max=info.shape[0]-1;$('trace-channel').value=clamp(Number($('trace-channel').value),0,info.shape[0]-1);document.querySelectorAll('#stage-table tr[data-layer]').forEach(row=>row.classList.toggle('selected',row.dataset.layer===info.name));renderTraceMetadata();}
function renderTraceMetadata(){const meta=state.activationMeta;if(!meta){$('trace-meta').textContent='尚未计算所选截面。点击计算后读取真实激活值。';return;}const mismatch=meta.layer!==state.traceLayer?.name||meta.time!==Number($('trace-time').value);$('trace-meta').textContent=`显示 ${meta.layer}, t=${meta.time}, revision=${meta.revision}${meta.revision!==state.status.revision?'（旧 latent）':''}${mismatch?'；与当前选择不同，需重新计算':''}；[C,H,W]=[${meta.shape}]；min=${fmt(meta.minimum)} max=${fmt(meta.maximum)}`;}
on('compute-trace','click',async()=>{clearError();await api('/api/trace',{layer:state.traceLayer.name,time:integer('trace-time',state.traceLayer.shape[1]-1)});await poll();});
on('trace-time','change',renderTraceMetadata);
on('follow-scalar','click',async()=>{switchTab('trace');selectStage(state.model.stages[0]);$('trace-time').value=state.t;$('trace-channel').value=state.c;await api('/api/trace',{layer:state.traceLayer.name,time:state.t});await poll();});
async function stepStage(direction){const old=state.traceLayer;const index=Number(old.name.split('.')[1]);const next=state.model.stages[clamp(index+direction,0,22)];const nextTime=clamp(Math.floor(Number($('trace-time').value)*next.shape[1]/old.shape[1]),0,next.shape[1]-1);selectStage(next);$('trace-time').value=nextTime;await api('/api/trace',{layer:next.name,time:nextTime});await poll();}
on('previous-stage','click',()=>stepStage(-1));on('next-stage','click',()=>stepStage(1));
on('stage-weights','click',async()=>{const name=state.traceLayer.name;const list=state.model.weights.filter(w=>w.name.startsWith(name+'.')).sort(naturalSort);if(!list.length)throw Error('此操作没有可学习的权重；其作用见上方公式。');$('weight-select').value=(list.find(w=>w.name.endsWith('.weight'))||list[0]).name;await loadWeight();switchTab('weights');});

async function loadActivation(){if(!state.status.trace)return;const meta=state.status.trace,request=++state.activationRequest;const c=integer('trace-channel',meta.shape[0]-1);$('trace-channel').value=c;const b=await binary(`/api/activation?id=${meta.id}&c=${c}`);if(request!==state.activationRequest)return;state.activation=b.array;state.activationMeta=meta;state.activationChannel=c;const [H,W]=b.shape;state.ay=clamp(state.ay,0,H-1);state.ax=clamp(state.ax,0,W-1);renderActivation();}
function renderActivation(){if(!state.activation)return;const [,H,W]=state.activationMeta.shape;const a=state.activation;let min=Infinity,max=-Infinity;for(const v of a){min=Math.min(min,v);max=Math.max(max,v);}plane($('activation-plane'),a,H,W,Math.max(Math.abs(min),Math.abs(max),1e-9),state.ay,state.ax);$('activation-value').textContent=`${state.activationMeta.layer}[c=${state.activationChannel}, t=${state.activationMeta.time}, y=${state.ay}, x=${state.ax}] = ${fmt(a[state.ay*W+state.ax])}；颜色范围 ±${Math.max(Math.abs(min),Math.abs(max)).toPrecision(4)}`;numberGrid($('activation-numbers'),a,H,W,state.ay,state.ax);renderTraceMetadata();}
on('trace-channel','change',loadActivation);on('activation-plane','click',e=>{if(!state.activation)return;[state.ay,state.ax]=pick(e,$('activation-plane'),state.activationMeta.shape[1],state.activationMeta.shape[2]);renderActivation();});

function renderResults(){const results=state.status.results;const select=$('result-select');const last=results.at(-1);if(!last)return;const current=select.value;const names=results.map(r=>r.id).join(',');if(select.dataset.ids!==names){select.replaceChildren();for(const result of results){const opt=document.createElement('option');opt.value=result.id;opt.textContent=`revision ${result.revision} / ${result.id}`;select.append(opt);}select.dataset.ids=names;select.value=last.id;selectResult();}else if(state.result){$('result-meta').textContent=`[${state.result.shape.join(', ')}] · ${state.result.seconds.toFixed(2)}s · revision ${state.result.revision}${state.result.revision!==state.status.revision?'（输入已修改，需重新 decode）':''}`;}}
function selectResult(){state.result=state.status.results.find(r=>r.id===$('result-select').value);if(!state.result)return;$('video').src=state.result.video;$('video-empty').hidden=true;$('rgb-frame').max=state.result.shape[1]-1;$('rgb-frame').value=0;state.rgb=null;$('rgb-value').textContent='读取帧后可检查浮点 RGB';$('rgb-plane').getContext('2d').clearRect(0,0,$('rgb-plane').width,$('rgb-plane').height);renderResults();loadRGB().catch(fail);}
on('result-select','change',selectResult);
async function loadRGB(){if(!state.result)throw Error('请先运行 decode');const result=state.result,frame=integer('rgb-frame',result.shape[1]-1),request=++state.rgbRequest;const b=await binary(`/api/rgb?id=${result.id}&frame=${frame}`);if(request!==state.rgbRequest)return;state.rgb=b.array;state.rgbShape=b.shape;state.rgbFrame=frame;state.rgbResult=result;state.ry=clamp(state.ry,0,b.shape[1]-1);state.rx=clamp(state.rx,0,b.shape[2]-1);drawRGB();}
function drawRGB(){const [,H,W]=state.rgbShape,canvas=$('rgb-plane');canvas.width=W;canvas.height=H;const ctx=canvas.getContext('2d'),img=ctx.createImageData(W,H);for(let i=0;i<H*W;i++)img.data.set([Math.round(state.rgb[i]*255),Math.round(state.rgb[H*W+i]*255),Math.round(state.rgb[2*H*W+i]*255),255],4*i);ctx.putImageData(img,0,0);ctx.strokeStyle='#ff00ff';ctx.strokeRect(state.rx-1,state.ry-1,3,3);const pos=state.ry*W+state.rx,values=[0,1,2].map(c=>state.rgb[c*H*W+pos]);$('rgb-value').textContent=`RGB[frame=${state.rgbFrame},y=${state.ry},x=${state.rx}] = [${values.map(fmt).join(', ')}]`;$('rgb-location').textContent=`8-bit 显示值 [${values.map(v=>Math.round(v*255)).join(', ')}]；revision ${state.rgbResult.revision}。输出第 ${state.rgbFrame} 帧来自未裁剪时间网格第 ${state.rgbFrame+3} 帧。`;}
on('load-frame','click',loadRGB);on('frame-from-video','click',()=>{if(!state.result)return;$('rgb-frame').value=clamp(Math.floor($('video').currentTime*state.result.fps),0,state.result.shape[1]-1);return loadRGB();});on('rgb-plane','click',e=>{if(!state.rgb)return;[state.ry,state.rx]=pick(e,$('rgb-plane'),state.rgbShape[1],state.rgbShape[2]);drawRGB();});
on('decode','click',async()=>{clearError();await api('/api/decode',{});await poll();});
function renderStatus(){if(!state.status)return;const s=state.status;const running=s.jobs.find(j=>j.state==='running');$('revision').textContent=`revision ${s.revision} · ${s.changed_scalars.toLocaleString()} modified`;$('decode').disabled=$('compute-trace').disabled=$('initialize').disabled=!!running;$('previous-stage').disabled=$('next-stage').disabled=$('follow-scalar').disabled=!!running;$('progress').value=running?running.progress:1;
 const last=s.jobs.at(-1);$('job-status').textContent=running?`${running.kind} rev ${running.revision} · ${(running.progress*100).toFixed(0)}% · ${(Date.now()/1000-running.started).toFixed(0)}s`:last?.state==='error'?`失败：${last.error}`:last?`${last.kind} 完成 · ${last.seconds?.toFixed(2)}s`:'就绪';
 $('edit-log').textContent=s.history.length?s.history.map(e=>`rev${e.revision} ${e.mode} [${e.index}] ${e.mode==='scalar'?'set':'add'} ${e.value} ; ${e.count} scalars`).join('\n'):'尚无修改';renderTraceMetadata();renderResults();}
async function poll(){const fresh=await api('/api/status');if(state.status&&fresh.revision<state.status.revision)return;state.status=fresh;renderStatus();const trace=state.status.trace;if(trace&&!state.completed.has(trace.id)){state.completed.add(trace.id);await loadActivation();}}
async function boot(){try{makeVolumes();state.model=await api('/api/model');state.status=await api('/api/status');$('machine').textContent=`${state.model.device} · ${state.model.parameter_count.toLocaleString()} parameters · 64 parameter tensors · ${state.model.top_level_operations} top-level operations`;$('preset').value=state.status.shape[2]===60?'full':'small';$('seed').value=state.status.seed;await reloadLatent(true);await setupWeights();renderStages();selectStage(state.model.stages[0]);document.querySelector('main').inert=false;setInterval(()=>poll().catch(fail),1500);}catch(e){fail(e);}}
boot();
